account/urls.py
from django.urls import path, reverse_lazy
from . import views
from django.contrib.auth import views as auth_views

app_name='account'

urlpatterns = [
    path('profile/', views.view_profile, name='view_profile'),
    path('profile/edit', views.edit_profile, name='edit_profile'),
    path("register/", views.register, name="register"),
]

home/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.HomeView.as_view()),
    path('about/', views.AboutView.as_view(), name = "about"),
    path('regions/', views.RegionView.as_view(), name = "regions"),
]

mysite/urls.py
import os
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.views.static import serve
from django.conf.urls.static import static

urlpatterns = [
    path('', include('home.urls')),
    path('explore/', include('places.urls')),
    path('account/', include('account.urls')),
    path('admin/', admin.site.urls),  # Keep
    path('account/', include('django.contrib.auth.urls')),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
]

# Serve the static HTML
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns += [
    url(r'^site/(?P<path>.*)$', serve,
        {'document_root': os.path.join(BASE_DIR, 'site'),
         'show_indexes': True},
        name='site_path'
        ),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# Serve the favicon - Keep for later
urlpatterns += [
    path('favicon.ico', serve, {
            'path': 'favicon.ico',
            'document_root': os.path.join(BASE_DIR, '/static'),
        }
    ),
]

# Switch to social login if it is configured - Keep for later
try:
    from . import github_settings
    social_login = 'registration/login_social.html'
    urlpatterns.insert(0,
                       path('account/login/', auth_views.LoginView.as_view(template_name=social_login))
                       )
    print('Using', social_login, 'as the login template')
except:
    print('Using registration/login.html as the login template')

places/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name='places'

urlpatterns = [
    path('', views.PlaceListView.as_view(), name='all'),
    path('<slug:slug>/', views.PlaceDetailView.as_view(), name="place_detail"),
    path('<slug:slug>/addreview/', views.addcomment, name='addcomment'),
    path('<slug:slug>/editreview/', views.editcomment, name='editcomment'),
]

# We use reverse_lazy in urls.py to delay looking up the view until all the paths are defined

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render
from django.views import View
from django.conf import settings
from places.models import Region, Place, Comment
from django.db.models import Avg, Case, When
# Create your views here.

# This is a little complex because we need to detect when we are
# running in various configurations


class HomeView(View):
    def get(self, request):
        print(request.get_host())
        host = request.get_host()
        top_places = Comment.objects.filter(status='True').values('place_id').annotate(average=Avg('rate')).order_by('-average').values('place_id')
        preserved = Case(*[When(id=place['place_id'], then=pos) for pos, place in enumerate(top_places)])
        place_list = Place.objects.filter(id__in=top_places).order_by(preserved)[:3]
        islocal = host.find('localhost') >= 0 or host.find('127.0.0.1') >= 0
        context = {
            'installed': settings.INSTALLED_APPS,
            'islocal': islocal,
            'place_list' : place_list
        }

        return render(request, 'home/main.html', context)

class AboutView(View):
    def get(self, request):
        return render(request, 'home/about.html')

class RegionView(View):
    def get(self, request):
        region_list = Region.objects.all()
        ctx = {'region_list' : region_list}
        return render(request, 'home/region.html', ctx)

home/templates/base_bootstrap.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
<title>{% block title %}{{ settings.APP_NAME }}{% endblock %}</title>
    <link rel="shortcut icon" href="{% static 'favicon.ico'  %}" />
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <link href='https://fonts.googleapis.com/css?family=Oxygen:400,300,700' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Lora' rel='stylesheet' type='text/css'>

    <script src="https://kit.fontawesome.com/a076d05399.js"></script>

    <script src="{% static 'js/functions.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles2.css' %}">
{% block head %} {% endblock %}

</head>
<body>
{% block navbar %} {% endblock %}
{% block header %} {% endblock %}
<div class="container">
{% block welcome %} {% endblock %}
{% block messages %}
    {% if messages %}
    {% for msg in messages %}
        <div class="alert alert-{{msg.level_tag}}" role="alert">
        {{msg.message}}
        </div>
    {% endfor %}
    {% endif %}
{% endblock %}
{% block content %}
{% endblock %}
</div>
{% block footer %} {% endblock %}
</body>
</html>

home/templates/base_menu.html
{% extends "base_bootstrap.html" %}
{% block navbar %}
{% load app_tags %}
{% load static %}
<header class='sticky-top'>
    <nav class="navbar navbar-expand-lg navbar-light menu-bar">
        <a class="navbar-brand" href="/">
            <img src="{% static 'images/logo.png' %}" width="75" height="42" alt="{{ settings.APP_NAME }}" loading="lazy">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <!-- https://stackoverflow.com/questions/22047251/django-dynamically-get-view-url-and-check-if-its-the-current-page -->
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              {% url 'places:all' as places %}
              <li {% if request.get_full_path == places %}class="active"{% endif %}>
                  <a class="nav-link" href="{% url 'places:all' %}">Explore</a>
              </li>
              {% url 'regions' as region %}
              <li {% if request.get_full_path == region %}class="active"{% endif %}>
                  <a class="nav-link" href="{% url 'regions' %}">Regions</a>
              </li>
              {% url 'about' as about %}
              <li {% if request.get_full_path == about %}class="active"{% endif %}>
                  <a class="nav-link" href="{% url 'about' %}">About</a>
              </li>
            </ul>

            <ul class="navbar-nav navbar-right my-2 my-lg-0">
                {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle">
                        {{user.username}}<b class="caret"></b>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'account:view_profile' %}">My Profile</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'logout' %}?next={{request.path}}">Logout</a>
                    </div>
                </li>
                {% else %}
                <li class="nav-item my-2 my-lg-0 mr-sm-2">
                    <a href="{% url 'login' %}?next={{request.path}}"><button class="btn btn-outline-primary">Login</button></a>
                </li>
                <li class="nav-item my-2 my-lg-0">
                    <a href="{% url 'account:register' %}?next={{request.path}}"><button class="btn btn-outline-success">Create Account</button></a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>
</header>

{% endblock %}

{% block footer %}
    <footer class="panel-footer">
        <div class="container">
            <div class="row">

                <!-- Qiuck links -->
                <section id="hours" class="col-12 col-md-4">
                    <span>Quick Links:</span><br>
                    <a href="{% url 'places:all' %}">Explore</a><br>
                    <a href="{% url 'regions' %}">Regions</a><br>
                    <a href="{% url 'about' %}">About</a>
                </section>

                <!-- Address -->
                <section id="address" class="col-12 col-md-4">
                    <span>Address:</span><br>
                    Vasai (W),<br>
                    Maharashtra, India
                </section>

                <!-- Testimonial -->
                <section id="testimonials" class="col-12 col-md-4">
                    <p>"One of the Best places to visit in Maharashtra if you want to visit tons of Diversity within an area!"</p>
                    <p>"Amazing Tourist Sites. Greenery everywhere and many Sea shores to visit... I'll be back again and again!!!"</p>
                </section>
            </div>
        </div>
    </footer>
{% endblock %}