home/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.HomeView.as_view()),
    path('about/', views.AboutView.as_view(), name = "about"),
    path('regions/', views.RegionView.as_view(), name = "regions"),
]

mysite/urls.py
import os
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.views.static import serve
from django.conf.urls.static import static

urlpatterns = [
    path('', include('home.urls')),
    path('explore/', include('places.urls')),
    path('account/', include('account.urls')),
    path('admin/', admin.site.urls),  # Keep
    path('account/', include('django.contrib.auth.urls')),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
]

# Serve the static HTML
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns += [
    url(r'^site/(?P<path>.*)$', serve,
        {'document_root': os.path.join(BASE_DIR, 'site'),
         'show_indexes': True},
        name='site_path'
        ),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# Serve the favicon - Keep for later
urlpatterns += [
    path('favicon.ico', serve, {
            'path': 'favicon.ico',
            'document_root': os.path.join(BASE_DIR, '/static'),
        }
    ),
]

# Switch to social login if it is configured - Keep for later
try:
    from . import github_settings
    social_login = 'registration/login_social.html'
    urlpatterns.insert(0,
                       path('account/login/', auth_views.LoginView.as_view(template_name=social_login))
                       )
    print('Using', social_login, 'as the login template')
except:
    print('Using registration/login.html as the login template')

places/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name='places'

urlpatterns = [
    path('', views.PlaceListView.as_view(), name='all'),
    path('<slug:slug>/', views.PlaceDetailView.as_view(), name="place_detail"),
    path('<slug:slug>/addreview/', views.addcomment, name='addcomment'),
    path('<slug:slug>/editreview/', views.editcomment, name='editcomment'),
]

# We use reverse_lazy in urls.py to delay looking up the view until all the paths are defined

places/models.py
from django.db import models
from django.core.validators import MinLengthValidator, MaxValueValidator, MinValueValidator
from django.conf import settings

from django.db.models import Avg, Count


class Place(models.Model) :
    title = models.CharField(
            max_length=100,
            validators=[MinLengthValidator(5, "Title must be greater than 5 characters")]
    )

    slug = models.SlugField(unique= True, blank=True)

    region = models.ForeignKey('Region', on_delete=models.CASCADE)

    category = models.ForeignKey('Category', on_delete=models.CASCADE)

    address = models.CharField(
            max_length=200,
            validators=[MinLengthValidator(10, "Address must be greater than 10 characters")]
    )

    #for the map
    latitude = models.DecimalField(max_digits=10, decimal_places=8,
    			validators=[MinValueValidator(-90, message="Latitude should be between -90 and 90"), MaxValueValidator(90, message="Latitude should be between -90 and 90")]
    	)
    longitude = models.DecimalField(max_digits=11, decimal_places=8,
    		 	validators=[MinValueValidator(-180, message="Longitude should be between -180 and 180"), MaxValueValidator(180, message="Longitude should be between -180 and 180")]
    	)

    map_place_id = models.CharField(
            null = True,
            max_length=200,
            help_text='(optional) Enter the maps place id for the site, e.g. ChIJpWiC6ZCu5zsRv1_fkb9WBeg'
    )

    streetview = models.CharField("Enable streetview?", max_length=10,choices=(('True', 'Yes'), ('False', 'No')), default='True',
    			help_text='Enable streetview or not.')

    description = models.TextField(null=True)
    # comments = models.ManyToManyField(settings.AUTH_USER_MODEL, 
    #     bthrough='Comment', related_name='comments_owned')

    featured_image = models.ImageField(upload_to="uploads/%Y/%m/%d", null=True)

    # Picture
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # Shows up in the admin list
    def __str__(self):
        return self.title

    def averagereview(self):
        reviews = Comment.objects.filter(place=self, status='True').aggregate(average=Avg('rate'))
        avg=0
        if reviews["average"] is not None:
            avg=float(reviews["average"])
        return avg

    def countreview(self):
        reviews = Comment.objects.filter(place=self, status='True').aggregate(count=Count('id'))
        cnt=0
        if reviews["count"] is not None:
            cnt = int(reviews["count"])
        return cnt

class Image(models.Model):
    images = models.ImageField(upload_to="uploads/%Y/%m/%d")
    place = models.ForeignKey(Place, on_delete=models.CASCADE)


class Category(models.Model):
    name = models.CharField(
            max_length=200,
            help_text='Enter a category (e.g. Church)',
            validators=[MinLengthValidator(2, "Category must be greater than 1 character")]
    )

    def __str__(self):
        """String for representing the Model object."""
        return self.name

class Region(models.Model):
    name = models.CharField(
            max_length=100,
            validators=[MinLengthValidator(2, "Region must be greater than 2 characters")]
    )

    image = models.ImageField(upload_to="uploads/%Y/%m/%d")

    def __str__(self):
        """String for representing the Model object."""
        return self.name

#Adding review system
class Comment(models.Model):
    STATUS = (
        ('True', 'True'),
        ('False', 'False'),
    )
    place=models.ForeignKey(Place,on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    subject = models.CharField(max_length=50, blank=True)
    comment = models.CharField(max_length=250,blank=True)
    rate = models.IntegerField(default=1)
    ip = models.CharField(max_length=20, blank=True)
    status=models.CharField(max_length=10,choices=STATUS, default='True')
    create_at=models.DateTimeField(auto_now_add=True)
    update_at=models.DateTimeField(auto_now=True)

    class Meta:
        constraints = [models.UniqueConstraint(fields=['place', 'user'], name='single_review')]

    def __str__(self):
        return self.subject

places/forms.py
from django import forms
from places.models import Place, Image, Comment
from django.core.files.uploadedfile import InMemoryUploadedFile
from places.humanize import naturalsize
from django.forms import ClearableFileInput


# Create the form class.
class PlaceModelForm(forms.ModelForm):
    max_upload_limit = 2 * 1024 * 1024
    max_upload_limit_text = naturalsize(max_upload_limit)

    # Call this 'picture' so it gets copied from the form to the in-memory model
    # It will not be the "bytes", it will be the "InMemoryUploadedFile"
    # because we need to pull out things like content_type

    # picture = forms.FileField(required=False, label='File to Upload <= '+max_upload_limit_text)
    # upload_field_name = 'picture'

    # Hint: this will need to be changed for use in the ads application :)
    class Meta:
        model = Place
        fields = ['title', 'address', 'category']  # Picture is manual

    # Validate the size of the picture
    def clean(self):
        cleaned_data = super().clean()
        pic = cleaned_data.get('picture')
        if pic is None:
            return
        if len(pic) > self.max_upload_limit:
            self.add_error('picture', "File must be < "+self.max_upload_limit_text+" bytes")

# https://docs.djangoproject.com/en/3.0/topics/http/file-uploads/
# https://stackoverflow.com/questions/2472422/django-file-upload-size-limit
# https://stackoverflow.com/questions/32007311/how-to-change-data-in-django-modelform
# https://docs.djangoproject.com/en/3.0/ref/forms/validation/#cleaning-and-validating-fields-that-depend-on-each-other

class ImageModelForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ['images']
        widgets = {
            'images': ClearableFileInput(attrs={'multiple': True}),
        }
        # widget is important to upload multiple files

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['subject', 'comment', 'rate']

places/views.py
from django.views import View
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse

from places.models import Place, Category, Image, Comment, Region
from places.forms import PlaceModelForm, ImageModelForm, CommentForm
from places.owner import OwnerListView, OwnerDetailView, OwnerCreateView, OwnerUpdateView, OwnerDeleteView

from places.utils import dump_queries
from django.db.models import Q
from django.contrib.humanize.templatetags.humanize import naturaltime
from django.db.utils import IntegrityError

from django.contrib import messages

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


# Create your views here.
class PlaceListView(OwnerListView):
    model = Place
    # By convention:
    template_name = "places/place_list.html"

    def get(self, request) :
        place_list = Place.objects.all()
        region_list = Region.objects.all()
        category_list = Category.objects.all()

        strval =  request.GET.get("search", False)
        strrate =  request.GET.get("searchByRating", False)
        strcat = request.GET.getlist("searchByCategory", False)
        strreg = request.GET.getlist("searchByRegion", False)
        if strrate :
            #Rating filter
            ids = [place.id for place in place_list if place.averagereview() >= float(strrate)]
            place_list = place_list.filter(id__in=ids)

        if strcat :
            # Category checkbox filter

            #First get the corresponding id's from table and convert to list
            category_id_list = Category.objects.filter(name__in=strcat).values_list('pk', flat=True)

            #then check the respective ids in the place table
            place_list = place_list.filter(category_id__in=category_id_list)
        if strreg :
            # Region checkbox filter

            #First get the corresponding id's from table and convert to list
            region_id_list = Region.objects.filter(name__in=strreg).values_list('pk', flat=True)

            #then check the respective ids in the place table
            place_list = place_list.filter(region_id__in=region_id_list)
        if strval :
            # Simple title-only search
            # objects = Post.objects.filter(title__contains=strval).select_related().order_by('-updated_at')[:10]

            # Multi-field search
            query = Q(title__icontains=strval)
            query.add(Q(description__icontains=strval), Q.OR)
            query.add(Q(address__icontains=strval), Q.OR)
            place_list = place_list.filter(query).select_related()

        objects = place_list.order_by('-updated_at')

        # Augment the post_list
        for obj in objects:
            obj.natural_updated = naturaltime(obj.updated_at)

        paginator = Paginator(objects, 5)
        page = self.request.GET.get('page')

        try:
            objects = paginator.page(page)
        except PageNotAnInteger:
            objects = paginator.page(1)
        except EmptyPage:
            objects = paginator.page(paginator.num_pages)

        get_copy = request.GET.copy()
        parameters = get_copy.pop('page', True) and get_copy.urlencode()

        ctx = {'place_list' : objects, 'region_list' : region_list, 'category_list' : category_list, 'search' : strval, 
        'searchByCategory' : strcat, 'searchByRegion' : strreg, 'searchByRating' : float(strrate), 'parameters' : parameters}
        dump_queries()
        return render(request, self.template_name, ctx)

class PlaceDetailView(OwnerDetailView):
    template_name = "places/place_detail.html"
    def get(self, request, slug) :
        place = get_object_or_404(Place, slug=slug)
        images = Image.objects.all().filter(place_id=place.id)
        
        comments = Comment.objects.filter(place_id=place.id,status='True').order_by('-update_at')

        review = None
        if request.user.is_authenticated:
            review = Comment.objects.filter(place_id=place.id,user_id=request.user.id)
        context = { 'place' : place, 'images' : images, 'comments': comments, 'review' : review }
        return render(request, self.template_name, context)

def addcomment(request,slug):
    url = request.META.get('HTTP_REFERER')  # get last url
    if url==None:   #if directly tried to use link redirect to original page
        url = '/explore/'+slug
    if request.user.is_authenticated:   #only allow logged in user to rate
        place = get_object_or_404(Place, slug=slug)
        if request.method == 'POST':  # check post
            form = CommentForm(request.POST)
            if form.is_valid():
                data = Comment()  # create relation with model
                data.subject = form.cleaned_data['subject']
                data.comment = form.cleaned_data['comment']
                data.rate = form.cleaned_data['rate']
                data.ip = request.META.get('REMOTE_ADDR')
                data.place_id=place.id
                current_user= request.user
                data.user_id=current_user.id
                try:
                    data.save()  # save data to table
                except IntegrityError:
                    messages.warning(request, "Something went wrong. Please try again later.")
                    return HttpResponseRedirect(url)
                messages.success(request, "Review sent successfully. Thank you for your interest.")
            return HttpResponseRedirect(url)
    else:
        return HttpResponseRedirect('/explore/'+slug)

    return HttpResponseRedirect(url)

def editcomment(request,slug):
    url = '/explore/'+slug
    if request.user.is_authenticated:   #only allow logged in user to rate
        place = get_object_or_404(Place, slug=slug)
        review = Comment.objects.filter(place_id=place.id, user_id=request.user.id)[0]
        if request.method == 'POST':  # check post
            form = CommentForm(request.POST)
            if form.is_valid():
                data = Comment.objects.filter(place_id=place.id).get(user_id=request.user.id)  # create relation with model
                data.subject = form.cleaned_data['subject']
                data.comment = form.cleaned_data['comment']
                data.rate = form.cleaned_data['rate']
                data.ip = request.META.get('REMOTE_ADDR')
                try:
                    data.save()  # save data to table
                except IntegrityError:
                    messages.warning(request, "Something went wrong. Please try again later.")
                    return HttpResponseRedirect(url)
                messages.success(request, "Review edited successfully.")
            return HttpResponseRedirect(url)
        else:
            return render(request, "places/edit_review.html", {'place' : place, 'review' : review})
    else:
        return HttpResponseRedirect('/explore/'+slug)

    return HttpResponseRedirect(url)

places/templates/places/comments.html
                            {% for rs in comments %}
                                <div class="single-review mt-3 px-2 border-bottom border-gray">
                                    <div class="review-heading">
                                        <div><i class="far fa-user"></i> {{ rs.user.first_name }}  {{ rs.user.last_name }}
                                        <span class="float-right"><i class="far fa-clock"></i> {{ rs.update_at.date }}</span></div>
                                        <div class="review-rating">
											{% if rs.rate <= 0  %}
											<span class="far fa-star wt-star"></span>
											{% elif rs.rate <= 0.5  %}
											<span class="fas fa-star-half-alt wt-star"></span>
											{% else %}
											<span class="fas fa-star wt-star"></span>
											{% endif %}

											{% if rs.rate <= 1  %}
											<span class="far fa-star wt-star"></span>
											{% elif rs.rate <= 1.5  %}
											<span class="fas fa-star-half-alt wt-star"></span>
											{% else %}
											<span class="fas fa-star wt-star"></span>
											{% endif %}

											{% if rs.rate <= 2  %}
											<span class="far fa-star wt-star"></span>
											{% elif rs.rate <= 2.5  %}
											<span class="fas fa-star-half-alt wt-star"></span>
											{% else %}
											<span class="fas fa-star wt-star"></span>
											{% endif %}

											{% if rs.rate <= 3  %}
											<span class="far fa-star wt-star"></span>
											{% elif rs.rate <= 3.5  %}
											<span class="fas fa-star-half-alt wt-star"></span>
											{% else %}
											<span class="fas fa-star wt-star"></span>
											{% endif %}

											{% if rs.rate <= 4  %}
											<span class="far fa-star wt-star"></span>
											{% elif rs.rate <= 4.5  %}
											<span class="fas fa-star-half-alt wt-star"></span>
											{% else %}
											<span class="fas fa-star wt-star"></span>
											{% endif %}
											<b class="pl-2">{{ rs.subject }}</b>
										</div>
									</div>
	                                <div class="review-body">
	                                    <p>{{ rs.comment }}</p>
	                                </div>
                                </div>
                            {% endfor %}

places/templates/places/edit_review.html
{% extends "base_menu.html" %}
{% load static %}
{% block title %}Edit Review - {{settings.APP_NAME}}{% endblock %}
{% block head %}
<link rel="stylesheet" href="{% static 'places/stars.css' %}">
{% endblock %}

{% load crispy_forms_tags %}

{% block content %}
<h2>Edit Review for {{ place.title }}</h2>
<div>
	            <form class="form-group" action="{% url 'places:editcomment' place.slug %}" method="post">
	            {% csrf_token %}
	                <div class="form-group">
	                    <input name="subject" class="input form-control" type="text" value="{{ review.subject }}" />
	                </div>
	                <div class="form-group">
	                    <textarea name="comment" class="input form-control">{{ review.comment }}</textarea>
	                </div>
	                <div class="form-group">
	                    <div class="input-rating">
	                        <strong class="text-uppercase">Your Rating:</strong>
	                        <span class="stars">
	                            <input type="radio" id="star5" name="rate" value="5" {% if review.rate == 5 %}checked{% endif %} required/>
	                            <label for="star5">5</label>
	                            <input type="radio" id="star4" name="rate" value="4" {% if review.rate == 4 %}checked{% endif %} required/>
	                            <label for="star4">4</label>
	                            <input type="radio" id="star3" name="rate" value="3" {% if review.rate == 3 %}checked{% endif %} required/>
	                            <label for="star3">3</label>
	                            <input type="radio" id="star2" name="rate" value="2" {% if review.rate == 2 %}checked{% endif %} required/>
	                            <label for="star2">2</label>
	                            <input type="radio" id="star1" name="rate" value="1" {% if review.rate == 1 %}checked{% endif %} required/>
	                            <label for="star1">1</label>
	                        </span>
	                    </div>
	                </div>
	                    <button class="btn btn-primary">Edit Review</button>
	            </form>
</div>
<a href="{% url 'places:place_detail' place.slug %}">Go Back</a>
{% endblock %}

places/templates/places/place_detail.html
{% extends "base_menu.html" %}
{% block title %} {{ place.title }} - {{settings.APP_NAME}} {% endblock %}

{% load static %}
{% block head %}
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>

	<script src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>
	<link rel="stylesheet" href="{% static 'places/stars.css' %}">

{% endblock %}

{% block content %}
	<div class="row">
		<div class="col-md-8">
			{% if images %}
			<div id="gallery" class="carousel slide" data-ride="carousel">
				<!-- Indicators -->
				<ul class="carousel-indicators">
					{% for image in images %}
						{% if forloop.counter0 == 0 %}
						<li data-target="#gallery" data-slide-to="0" class="active"></li>
						{% else %}
						<li data-target="#gallery" data-slide-to="{{ forloop.counter0 }}"></li>
						{% endif %}
					{% endfor %}
				</ul>

				<!-- The slideshow -->
				<div class="carousel-inner p-0">
					{% for image in images %}
						{% if forloop.counter0 == 0 %}
						<div class="carousel-item active wt-carousel-dimensions">
							<img src="{{ image.images.url }}" class="d-block">
						</div>
						{% else %}
						<div class="carousel-item wt-carousel-dimensions">
							<img src="{{ image.images.url }}" class="d-block">
						</div>
						{% endif %}
					{% endfor %}
				</div>

				<!-- Left and right controls -->
				<a class="carousel-control-prev" href="#gallery" data-slide="prev">
					<span class="carousel-control-prev-icon"></span>
				</a>
				<a class="carousel-control-next" href="#gallery" data-slide="next">
					<span class="carousel-control-next-icon"></span>
				</a>
			</div>
			{% endif %}
		</div>
		<div class="col-md-4 pt-1 pt-md-5">
			<h1>{{ place.title }}</h1>
			<h5>{{ place.region }}</h5>
			<h6>{{ place.category }}</h6>
			<div>
				<div class="place-rating">
						{% if place.averagereview <= 0  %}
						<span class="far fa-star wt-star"></span>
						{% elif place.averagereview <= 0.5  %}
						<span class="fas fa-star-half-alt wt-star"></span>
						{% else %}
						<span class="fas fa-star wt-star"></span>
						{% endif %}

						{% if place.averagereview <= 1  %}
						<span class="far fa-star wt-star"></span>
						{% elif place.averagereview <= 1.5  %}
						<span class="fas fa-star-half-alt wt-star"></span>
						{% else %}
						<span class="fas fa-star wt-star"></span>
						{% endif %}

						{% if place.averagereview <= 2  %}
						<span class="far fa-star wt-star"></span>
						{% elif place.averagereview <= 2.5  %}
						<span class="fas fa-star-half-alt wt-star"></span>
						{% else %}
						<span class="fas fa-star wt-star"></span>
						{% endif %}

						{% if place.averagereview <= 3  %}
						<span class="far fa-star wt-star"></span>
						{% elif place.averagereview <= 3.5  %}
						<span class="fas fa-star-half-alt wt-star"></span>
						{% else %}
						<span class="fas fa-star wt-star"></span>
						{% endif %}

						{% if place.averagereview <= 4  %}
						<span class="far fa-star wt-star"></span>
						{% elif place.averagereview <= 4.5  %}
						<span class="fas fa-star-half-alt wt-star"></span>
						{% else %}
						<span class="fas fa-star wt-star"></span>
						{% endif %}
						{{ place.averagereview |stringformat:".1f"}} stars
				</div>
                <a href="#reviews"> {{ place.countreview }}  Review(s) / Add Review</a>
            </div>
            <hr>
            <div>
            	<b>Address:</b>
            	<p>{{ place.address }}</p>
            </div>
		</div>
	</div>
	<hr>
	{% ifequal place.streetview 'True' %}
	<div class="row mt-3">
		<div class="col-12">
			<iframe
			  width="100%"
			  height="600px"
			  frameborder="0" style="border:0"
			  	src="https://www.google.com/maps/embed/v1/streetview?key={{ settings.GOOGLE_MAPS_API_KEY }}&location={{ place.latitude }},{{ place.longitude }}" allowfullscreen>
			</iframe>
		</div>
	</div>
	<hr>
	{% endifequal %}
	<div class="row">
		<div class="col-12 twoColumns">
			<p>{{ place.description }}</p>
		</div>
	</div>
	<hr>
	<div class="row">
		<div class="col-md-6">
			<iframe
			  width="100%"
			  height="400px"
			  frameborder="0" style="border:0"
			  {% if place.map_place_id %}
			  	src="https://www.google.com/maps/embed/v1/place?key={{ settings.GOOGLE_MAPS_API_KEY }}&q=place_id:{{ place.map_place_id }}" allowfullscreen>
			  {% else %}
			  	src="https://www.google.com/maps/embed/v1/search?key={{ settings.GOOGLE_MAPS_API_KEY }}&q={{ place.latitude }},{{ place.longitude }}" allowfullscreen>
			  {% endif %}
			</iframe>
		</div>
		<div class="col-md-6 mt-3">
        	{% load crispy_forms_tags %}
        	{% if review %}
        		{% for review in review %}
	        	<h4>Your Review</h4>
	        	{% if messages %}
	               	{% for message in messages %}
	                    <div class="alert alert-{{message.tags}}" role="alert">
	                        {{ message }}
	                    </div>
	                {% endfor %}
	            {% endif %}
	        	<i class="far fa-clock"></i> {{ review.update_at.date }}
	            <div class="review-rating">
					{% if review.rate <= 0  %}
					<span class="far fa-star wt-star"></span>
					{% elif review.rate <= 0.5  %}
					<span class="fas fa-star-half-alt wt-star"></span>
					{% else %}
					<span class="fas fa-star wt-star"></span>
					{% endif %}
					{% if review.rate <= 1  %}
					<span class="far fa-star wt-star"></span>
					{% elif review.rate <= 1.5  %}
					<span class="fas fa-star-half-alt wt-star"></span>
					{% else %}
					<span class="fas fa-star wt-star"></span>
					{% endif %}
					{% if review.rate <= 2  %}
					<span class="far fa-star wt-star"></span>
					{% elif review.rate <= 2.5  %}
					<span class="fas fa-star-half-alt wt-star"></span>
					{% else %}
					<span class="fas fa-star wt-star"></span>
					{% endif %}
					{% if review.rate <= 3  %}
					<span class="far fa-star wt-star"></span>
					{% elif review.rate <= 3.5  %}
					<span class="fas fa-star-half-alt wt-star"></span>
					{% else %}
					<span class="fas fa-star wt-star"></span>
					{% endif %}
					{% if review.rate <= 4  %}
					<span class="far fa-star wt-star"></span>
					{% elif review.rate <= 4.5  %}
					<span class="fas fa-star-half-alt wt-star"></span>
					{% else %}
					<span class="fas fa-star wt-star"></span>
					{% endif %}
					<b class="pl-2">{{ review.subject }}</b>
				</div>
	            <p>{{ review.comment }}</p>
	            <a href="{% url 'places:editcomment' place.slug %}" class="btn btn-primary">Edit Review</a>
	            {% endfor %}
        	{% else %}
	            <h4>Write Your Review</h4>
	            {% if messages %}
	                {% for message in messages %}
	                    <div class="alert alert-{{message.tags}}" role="alert">
	                        {{ message }}
	                    </div>
	                {% endfor %}
	            {% endif %}
	            <form class="form-group" action="{% url 'places:addcomment' place.slug %}" method="post">
	            {% csrf_token %}
	                <div class="form-group">
	                    <input name="subject" class="input form-control" type="text" placeholder="Your subject" />
	                </div>
	                <div class="form-group">
	                    <textarea name="comment" class="input form-control" placeholder="Your review"></textarea>
	                </div>
	                <div class="form-group">
	                    <div class="input-rating">
	                        <strong class="text-uppercase">Your Rating:</strong>
	                        <span class="stars">
	                            <input type="radio" id="star5" name="rate" value="5" required/>
	                            <label for="star5">5</label>
	                            <input type="radio" id="star4" name="rate" value="4" required/>
	                            <label for="star4">4</label>
	                            <input type="radio" id="star3" name="rate" value="3" required/>
	                            <label for="star3">3</label>
	                            <input type="radio" id="star2" name="rate" value="2" required/>
	                            <label for="star2">2</label>
	                            <input type="radio" id="star1" name="rate" value="1" required/>
	                            <label for="star1">1</label>
	                        </span>
	                    </div>
	                </div>
	                {% if user.is_authenticated %}
	                    <button class="btn btn-success">Submit</button>
	                {% else %}
	                    You must be logged in to post a review
	                {% endif %}
	            </form>
            {% endif %}
        </div>
	</div>
	<hr>
	<div class="row">
		<div class="col-md-12">
	            <h4 id='reviews'>Reviews ({{ place.countreview }})</h4>
	            <div class="row">
	                <div class="col-md-12">
	                    <div class="place-reviews">
	                    	{% include 'places/comments.html' %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}